language: node_js
node_js:
    - lts/*
cache: yarn
notifications:
    email: false
script: yarn verify
jobs:
    include:
        - stage: release
          node_js: lts/*
          deploy:
              provider: script
              skip_cleanup: true
              script:
                  - npx semantic-release
env:
    global:
        - secure: gPTUfQ04So7tIq0HJ9YXdzST+riPx9dcChzrBsNe6kITeu0ahWw78zqly/BUfEEqfza2tFe8ipZ8+Hz3aHpQ7WLvlKR4eR0anD/wS9e8MZbsz2mjpMOLIHYpwEdnCQ82GWkbA0N1f4ed6/ju2QDtpU3uV9A/fS8df8Dw/Cy94/65sOT+xgfC7jotv4SGTUNWCKzzrtnlrM8Yz5okHIy/sVKYRfcY6NOs4Aqhc6P0UDL9E6luNEazSaXO/nJuj3+8cEwOXai8rx36b+o1s4kNrqd3WJDjMm8m9HesUs3w9iN9/mj9SORGIqyOZA5272m9gysSiCuqdfe5J+c0LQiAM0r7eHmxJ2pgBzu6OCtrTekYM2C06tTMJWr6VWMEIvrgUFS6H5iSxhKtVcE0CiRYBr0B5s0g482Jl7GyCLJco+VVkjmxzDbzU5HYpd2H76vPtPgWHD9ovpAKNx/9qshVMdtnGPSYZN13K/XmycF0SNPBZZDm/7PILxbDn8NDXDlHuoZqO9YDHn/uw8erEcv3RIGTAZiTByjrTTAbCAgPFeeHKFMg81DKo0V3/nbcCpvrRyo414D9wvXgeO6wcaVKgPihDVdub8NvUjAAYYNrM6YL2CsOkxvLbUHPWVww6LhdAZcXrMpJRgNphu5HV5KLsptCte19KMVyWPJUkWQxjkw=
        - secure: uQpY7GxQV+BCfd+o19BVK/E7uQeqJux62l7joljwk21B9LxRnTW8sPsqASuR2t39jQHuSyDhJBa6Co02GxN7VoZ51zokgqlSWiI8VIU1vvJ2gauGOPbl8ekQZfXFCRZP/JiR2uwcnmPA4PQ6hig8MGemgaVZVBcYJjZkp5dtG/Jf6oj5S1jkt/JAPzAtZtBGI76Gs36ylQ4sXm/feoFSysTDuWOEn2UocRFkVJ5MrXqysuyWqIX9iaxp1ZR9KvaFEkwh74hKavtDzyHBSHiYErBn7+UiCwtrEPMP9fOjPC3FjUmyo4BUQ7z3TRJXhV4B2cW9I0uMKptydS8YNV2WJcBOREBKL/1sJ4Z06fTBAcC798/Q66eYdfY+TeejuYWHucY9q/9Swig3i5j5yMcQpYm2nnTArXsSR9A+52lCNBkV8oKZiKz1NtJ1/sC1irLsjUG5Y60+3kxrbZ2TjI+kzLahLyxr5JHlzZidzDMkVIvNzr729vp601XLU9WwiU5KgKtiApYJuH5ZiSzSINrZMnwOsCQGUaNJY3sHy0i0cSvBpdFaQhz5FZSQgaG9ZrsibE6HqEztcjCO71W2zJbxbaUGgPmDVVFQd2CmzSsG/AVnuelZ4l2YTZtC94xYY1cngNG3x5VfUb61sxjHQqT/irnnO5WHcNQy8Ravm4lBcLo=
